### ISSUE TITLE
Nothing happens on transaction...

### ISSUE THREAD

**Issue by teletonn** [cybor97/duckbuybot#1]
Hi bro! First of all I want to thank you for you wonderful work. I see that you kill much time for it.
Well, thanks for this, and go on, you are very cool.

And now I have a little question. I've installed all this things, got all api keys, renamed variable in .env for coinmarketcap key to get it work. Bot adds chat id and token address, even show holders number and they are in db too. But when transaction happens (when bot is running with pm2.... bot and cron) nothing happens with him not in time of transaction no later in 10, 20, 100 minutes no messages.
Can you help me and tell what is the problem in code? I didn't change it on .env, everything was cloned from this rep.
Thanks again and have a nice day!
Если говоришь по русски можем так ))

**Comment by cybor97** [comment]
Hi
Is the transaction a purchase performed via one of the DEXes? Also could you please share logs or/and the transaction in question?

**Comment by teletonn** [comment]
yes, they go with ston.fi

**Comment by teletonn** [comment]
and there is no pool address in db

**Comment by teletonn** [comment]
now i see in log that its too many requests, there was NOT coin in ticker so it tries to get holder, there is too many. now will se how its will go with only mini token.

**Comment by teletonn** [comment]
[2024-07-11T17:40:20.755Z] [32minfo[39m: Starting app...
[2024-07-11T17:40:21.667Z] [32minfo[39m: Data Source has been initialized!
[2024-07-11T17:40:21.680Z] [32minfo[39m: Cron inited
[2024-07-11T17:40:21.884Z] [32minfo[39m: Fetching holders for EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 0-1000/unknown
[2024-07-11T17:40:21.961Z] [32minfo[39m: Syncing EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 0/5. First sync: false
[2024-07-11T17:40:21.962Z] [32minfo[39m: Syncing EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 1/5. First sync: false
[2024-07-11T17:40:21.962Z] [32minfo[39m: Syncing EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 2/5. First sync: false
[2024-07-11T17:40:21.962Z] [32minfo[39m: Syncing EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 3/5. First sync: false
[2024-07-11T17:40:21.963Z] [32minfo[39m: Syncing EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 4/5. First sync: false
[2024-07-11T17:40:22.333Z] [33mwarn[39m: No conmarketcapId for EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7

**Comment by teletonn** [comment]
what coin can I test so I see transactions?
can I make a channel where so bot send there all the coin buys and sells?

**Comment by cybor97** [comment]
> and there is no pool address in db

It's ok, it's not used for detection, just wallet type which is specified in DEX_CONFIG

> what coin can I test so I see transactions

Basically any, e.g. https://tonviewer.com/EQBTcytZjdZwFLj6TO7CeGvn4aMmqXvbX-nODiApbd011gT3

> can I make a channel where so bot send there all the coin buys and sells

Sure, but current implementation will only send events of token purchases, not sells

**Comment by teletonn** [comment]
ok, I've used the token that is in my log if its ok. 
Now I made a new wallet, go to exchange in ton keeper, there find my token, and make a buy.
Waiting 10 minutes. or it must say about it immediately?

**Comment by cybor97** [comment]
It takes about 10 mins 
Also by default it will only work for STON.fi or DeDust dexes, if you need to use with some other you'll have to set up DEX_CONFIG

**Comment by teletonn** [comment]
exchange and lp only on ston.fi, so I can buy only with it. and other bot shows everything ok, but mine is not.

**Comment by teletonn** [comment]
I can give you admin in group @jettontrend and you can test it yourself with any token.
if you want and have time for this of course.

**Comment by cybor97** [comment]
I cannot see any recent transactions for the address you mentioned in tonviewer https://tonviewer.com/EQCWHrRdqomhegznML6_Z4v7TAmiQmnQOy6heab6g5c9jvO7 . 

Is it the same token?
Also could you please share the transaction id?

**Comment by teletonn** [comment]
https://tonviewer.com/transaction/8103a3cfe43bfcdd484d281c33280296464c7040e613bbe07a83d0dd718ff214

**Comment by teletonn** [comment]
DEX_CONFIG=EQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4TiUt:STON.fi,EQCMLWHcGz4AkNTnP6CTMG0Guo68_DTZ5Dc-AGHqtN8leJ0h:DeDust

**Comment by cybor97** [comment]
I guess we found it :)

**Comment by teletonn** [comment]
I'm dumb? ))

**Comment by teletonn** [comment]
Ithought thats the router:
https://tonviewer.com/EQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4TiUt

**Comment by cybor97** [comment]
> I'm dumb? ))

Nope, just makes sense to add to README as it really can be confusing

You should NOT specify addresses in DEX_CONFIG, only Wallet/Contract type for pools

![image](https://github.com/cybor97/duckbuybot/assets/9701800/5e1d3c09-c870-4852-99b6-a4f19a402fd4)

**Comment by cybor97** [comment]
Also it's not even mandatory, by default
```ts
process.env.DEX_CONFIG ?? "stonfi_router:STON.fi,dedust_vault:DeDust";
```

**Comment by teletonn** [comment]
DEX_CONFIG=stonfi_router:STON.fi,dedust_vault:DeDust

**Comment by teletonn** [comment]
like that?

**Comment by teletonn** [comment]
> Also it's not even mandatory, by default
> 
> ```ts
> process.env.DEX_CONFIG ?? "stonfi_router:STON.fi,dedust_vault:DeDust";
> ```

I saw this in code, I thought its template to take address from env

**Comment by teletonn** [comment]
make another buy or it must show that was 30 minutes ago?

**Comment by teletonn** [comment]
I've edited .env and restarted pm2

**Comment by cybor97** [comment]
> make another buy or it must show that was 30 minutes ago?

You'll have to do another swap, most probably it already updated LT for addresses so won't trigger to the "old" transaction

**Comment by teletonn** [comment]
I've made, but no reaction.
LT column in holders table is empty...

**Comment by teletonn** [comment]
WOW! YES! They all recived!

**Comment by teletonn** [comment]
Buttons goes to buy DUCk token, we need to make a link to current, ok, try to figure it out. And how to make all tokens in one chat, I want to make something like rating.. Thanks again for your help and code, you're very cool , bro!

**Comment by teletonn** [comment]
![image](https://github.com/user-attachments/assets/a2292b88-9935-48dd-8b29-c6d8761910ab)
Here is how LT loaded, not all, don't know why. maybe they will be loaded later..

**Comment by cybor97** [comment]
> Here is how LT loaded, not all, don't know why. maybe they will be loaded later..

It's expected, most likely there are no recent token transfers for these addresses

**Comment by teletonn** [comment]
It can be great open source project, I think many developers will be use it as a start point! It have everything for start, just need some adjustments. You can make commercial version and have good money for it, also open source version can be with start functions only. for not big price 100-200$ it will be sold like hot cakes. ))

**Comment by cybor97** [comment]
> It can be great open source project, I think many developers will be use it as a start point! It have everything for start, just need some adjustments. You can make commercial version and have good money for it, also open source version can be with start functions only. for not big price 100-200$ it will be sold like hot cakes. ))

Let's discuss that in Telegram itself if you don't mind, there's a link in my profile :)
This specific repository is 💯 free & open source

**Comment by cybor97** [comment]
Closing this issue. I'll check out what can be done in terms of refactoring and doc improvement. But that's not closely related

Also feel free to create a PR for DUCK links issue :) 
I won't have time for that until the next week unfortunately
