### ISSUE TITLE
Links lead to purchase DUCK coin, should be configurable

### ISSUE THREAD

**Issue by cybor97** [cybor97/duckbuybot#2]
Buttons goes to buy DUCk token, we need to make a link to current
_Originally posted by @teletonn in https://github.com/cybor97/duckbuybot/issues/1#issuecomment-2223641576_

**Comment by teletonn** [comment]
I don't know how to du pull request, but for everybdy who needs it right now, you just need to edit src/utils/telegram.ts at lines 79-90:
`
  const inline_keyboard = [
    [
      {
        text: "Buy with DeDust.io",
        url: `https://dedust.io/swap/TON/${config.tokenAddress}`,
      },
      {
        text: "Buy with STON.fi",
        url: `https://app.ston.fi/swap?chartVisible=false&ft=TON&tt=${config.tokenAddress}`,
      },
    ],
  ];
`

**Comment by cybor97** [comment]
> I don't know how to du pull request
@teletonn 

## Just click on fork in code tab
![Screenshot 2024-07-16 at 09 13 24](https://github.com/user-attachments/assets/ba10f96a-8a30-4a63-8d16-0ea1f9850724)
![Screenshot 2024-07-16 at 09 14 16](https://github.com/user-attachments/assets/7095607d-05bd-4b43-8ad6-9716cbc1b4dc)

## And then after adding your changes just click on Contribute -> Open pull request
![Screenshot 2024-07-16 at 09 14 49](https://github.com/user-attachments/assets/696edb30-52a7-4837-85ff-0925b078d700)
![Screenshot 2024-07-16 at 09 15 10](https://github.com/user-attachments/assets/4196f105-edcc-4814-9ac6-81ab72544aa7)

**Comment by cybor97** [comment]
Already solved by @teletonn
